{
    rm="rm -rfv";
    cp="cp -av --reflink=auto";
    mv="mv -v";
    du="du -sh";
    mkdir="mkdir -p";
    less="less -r";
    more="less -r";
    reboot="sudo reboot";
    poweroff="sudo poweroff";
    btrfs-du="btrfs fi du -s --human-readable";
    btrfs-list="sudo btrfs subvolume list / -t";
    btrfs-df="btrfs filesystem df /";
    sudo="sudo ";
    rsync="rsync -Pva";
    mount="sudo mount";
    umount="sudo umount";
    feh-svg="feh --magick-timeout 1";
    neofetch="clear; neofetch";
    aria2c="aria2c --file-allocation=none";
    zshrc-reload="reload-zshrc";
    xclip="xclip -selection clipboard";
    df="df -h";
    fex="nautilus .";
    ffprobe="ffprobe -hide_banner";
    ffmpeg="ffmpeg -hide_banner";
    ffplay="ffplay -hide_banner";
    ":q"="exit";
    sl="ls";
    sensors="clear; sensors";
    lolfetch="neofetch | lolcat -F 0.5";
    "-g sd"="~/ScratchArea";
    "-g dl"="~/Downloads";
    "-g \"...\""="../..";
    test="echo test";
    ls="exa -lhgbHm --git ";
    lst="exa -lhgbHmT --git";
    lsa="exa -lhgbHma --git";
    update="sudo nixos-rebuild switch"; 
}